#include <array>
#include <bitset>
#include <chrono>
#include <complex>
#include <cstddef>
#include <cstdint>
#include <deque>
#include <filesystem>
#include <iostream>
#include <list>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <system_error>
#include <variant>
#include <vector>

#include "v2/variant.h"

// void test_variant_20_types() {
// 	// holds alternative 10: long double
// 	dev::variant<std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>>
// 	    v(1.414L);
// 	(void)v;
// }

// void test_variant_40_types() {
// 	// holds alternative 33: std::map<std::string,int>
// 	dev::variant<std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds>
// 	    v(std::map<std::string, int>{
// 	        {"a", 1}
//     });
// 	(void)v;
// }

// void test_variant_60_types() {
// 	// holds alternative 0: std::int8_t
// 	dev::variant<std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char>
// 	v(std::int8_t{42});
// 	(void)v;
// }

// void test_variant_80_types() {
// 	// holds alternative 27: std::array<int,4>
// 	dev::variant<std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>>
// 	    v(std::array<int, 4>{1, 2, 3, 4});
// 	(void)v;
// }

// void test_variant_100_types() {
// 	// holds alternative 2: std::int32_t
// 	dev::variant<std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t>
// 	v(std::int32_t{100000});
// 	(void)v;
// }

// void test_variant_120_types() {
// 	// holds alternative 115: std::vector<double>
// 	dev::variant<std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>>
// 	    v(std::vector<double>{1.0, 2.0});
// 	(void)v;
// }

// void test_variant_140_types() {
// 	// holds alternative 116: std::list<int>
// 	dev::variant<std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t>
// 	    v(std::list<int>{10, 20});
// 	(void)v;
// }

// void test_variant_160_types() {
// 	// holds alternative 49: std::int16_t
// 	dev::variant<std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool>
// 	v(std::int16_t{1000});
// 	(void)v;
// }

// void test_variant_180_types() {
// 	// holds alternative 142: std::filesystem::path
// 	dev::variant<std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>,
// 	             std::bitset<16>,
// 	             std::complex<float>,
// 	             std::complex<double>,
// 	             std::chrono::milliseconds,
// 	             std::chrono::seconds,
// 	             std::byte,
// 	             std::monostate,
// 	             std::size_t,
// 	             std::ptrdiff_t,
// 	             std::string_view,
// 	             std::filesystem::path,
// 	             std::error_code,
// 	             std::int8_t,
// 	             std::int16_t,
// 	             std::int32_t,
// 	             std::int64_t,
// 	             std::uint8_t,
// 	             std::uint16_t,
// 	             std::uint32_t,
// 	             std::uint64_t,
// 	             float,
// 	             double,
// 	             long double,
// 	             char,
// 	             unsigned char,
// 	             signed char,
// 	             wchar_t,
// 	             bool,
// 	             std::string,
// 	             std::wstring,
// 	             std::vector<int>,
// 	             std::vector<double>,
// 	             std::list<int>,
// 	             std::deque<int>,
// 	             std::pair<int, int>,
// 	             std::pair<std::string, double>,
// 	             std::optional<int>,
// 	             std::optional<std::string>,
// 	             std::optional<double>,
// 	             std::array<int, 4>,
// 	             std::array<char, 8>,
// 	             std::array<double, 2>,
// 	             std::set<int>,
// 	             std::set<std::string>,
// 	             std::map<int, int>,
// 	             std::map<std::string, int>,
// 	             std::shared_ptr<int>,
// 	             std::bitset<8>>
// 	    v(std::filesystem::path{"/tmp"});
// 	(void)v;
// }

void test_variant_200_types() {
	// holds alternative 97: std::int16_t
	dev::variant<std::int8_t,
	             std::int16_t,
	             std::int32_t,
	             std::int64_t,
	             std::uint8_t,
	             std::uint16_t,
	             std::uint32_t,
	             std::uint64_t,
	             float,
	             double,
	             long double,
	             char,
	             unsigned char,
	             signed char,
	             wchar_t,
	             bool,
	             std::string,
	             std::wstring,
	             std::vector<int>,
	             std::vector<double>,
	             std::list<int>,
	             std::deque<int>,
	             std::pair<int, int>,
	             std::pair<std::string, double>,
	             std::optional<int>,
	             std::optional<std::string>,
	             std::optional<double>,
	             std::array<int, 4>,
	             std::array<char, 8>,
	             std::array<double, 2>,
	             std::set<int>,
	             std::set<std::string>,
	             std::map<int, int>,
	             std::map<std::string, int>,
	             std::shared_ptr<int>,
	             std::bitset<8>,
	             std::bitset<16>,
	             std::complex<float>,
	             std::complex<double>,
	             std::chrono::milliseconds,
	             std::chrono::seconds,
	             std::byte,
	             std::monostate,
	             std::size_t,
	             std::ptrdiff_t,
	             std::string_view,
	             std::filesystem::path,
	             std::error_code,
	             std::int8_t,
	             std::int16_t,
	             std::int32_t,
	             std::int64_t,
	             std::uint8_t,
	             std::uint16_t,
	             std::uint32_t,
	             std::uint64_t,
	             float,
	             double,
	             long double,
	             char,
	             unsigned char,
	             signed char,
	             wchar_t,
	             bool,
	             std::string,
	             std::wstring,
	             std::vector<int>,
	             std::vector<double>,
	             std::list<int>,
	             std::deque<int>,
	             std::pair<int, int>,
	             std::pair<std::string, double>,
	             std::optional<int>,
	             std::optional<std::string>,
	             std::optional<double>,
	             std::array<int, 4>,
	             std::array<char, 8>,
	             std::array<double, 2>,
	             std::set<int>,
	             std::set<std::string>,
	             std::map<int, int>,
	             std::map<std::string, int>,
	             std::shared_ptr<int>,
	             std::bitset<8>,
	             std::bitset<16>,
	             std::complex<float>,
	             std::complex<double>,
	             std::chrono::milliseconds,
	             std::chrono::seconds,
	             std::byte,
	             std::monostate,
	             std::size_t,
	             std::ptrdiff_t,
	             std::string_view,
	             std::filesystem::path,
	             std::error_code,
	             std::int8_t,
	             std::int16_t,
	             std::int32_t,
	             std::int64_t,
	             std::uint8_t,
	             std::uint16_t,
	             std::uint32_t,
	             std::uint64_t,
	             float,
	             double,
	             long double,
	             char,
	             unsigned char,
	             signed char,
	             wchar_t,
	             bool,
	             std::string,
	             std::wstring,
	             std::vector<int>,
	             std::vector<double>,
	             std::list<int>,
	             std::deque<int>,
	             std::pair<int, int>,
	             std::pair<std::string, double>,
	             std::optional<int>,
	             std::optional<std::string>,
	             std::optional<double>,
	             std::array<int, 4>,
	             std::array<char, 8>,
	             std::array<double, 2>,
	             std::set<int>,
	             std::set<std::string>,
	             std::map<int, int>,
	             std::map<std::string, int>,
	             std::shared_ptr<int>,
	             std::bitset<8>,
	             std::bitset<16>,
	             std::complex<float>,
	             std::complex<double>,
	             std::chrono::milliseconds,
	             std::chrono::seconds,
	             std::byte,
	             std::monostate,
	             std::size_t,
	             std::ptrdiff_t,
	             std::string_view,
	             std::filesystem::path,
	             std::error_code,
	             std::int8_t,
	             std::int16_t,
	             std::int32_t,
	             std::int64_t,
	             std::uint8_t,
	             std::uint16_t,
	             std::uint32_t,
	             std::uint64_t,
	             float,
	             double,
	             long double,
	             char,
	             unsigned char,
	             signed char,
	             wchar_t,
	             bool,
	             std::string,
	             std::wstring,
	             std::vector<int>,
	             std::vector<double>,
	             std::list<int>,
	             std::deque<int>,
	             std::pair<int, int>,
	             std::pair<std::string, double>,
	             std::optional<int>,
	             std::optional<std::string>,
	             std::optional<double>,
	             std::array<int, 4>,
	             std::array<char, 8>,
	             std::array<double, 2>,
	             std::set<int>,
	             std::set<std::string>,
	             std::map<int, int>,
	             std::map<std::string, int>,
	             std::shared_ptr<int>,
	             std::bitset<8>,
	             std::bitset<16>,
	             std::complex<float>,
	             std::complex<double>,
	             std::chrono::milliseconds,
	             std::chrono::seconds,
	             std::byte,
	             std::monostate,
	             std::size_t,
	             std::ptrdiff_t,
	             std::string_view,
	             std::filesystem::path,
	             std::error_code,
	             std::int8_t,
	             std::int16_t,
	             std::int32_t,
	             std::int64_t,
	             std::uint8_t,
	             std::uint16_t,
	             std::uint32_t,
	             std::uint64_t>
	v(std::int16_t{1000});
	(void)v;
}

int main() {
	// test_variant_20_types();
	// test_variant_40_types();
	// test_variant_60_types();
	// test_variant_80_types();
	// test_variant_100_types();
	// test_variant_120_types();
	// test_variant_140_types();
	// test_variant_160_types();
	// test_variant_180_types();
	test_variant_200_types();
	std::cout << "All tests passed.\n";
}