# Compute the length of a list
function(ListLength list_var list_len)
    set(_len 0)
    foreach(element IN LISTS ${list_var})
        if("${element}" STREQUAL "")
            continue()
        endif()
        math(EXPR "_len" "${_len} + 1")
    endforeach()
    set("${list_len}" "${_len}" PARENT_SCOPE)
endfunction()

set(len 0)
set(myList 1 2 3 4 5)
ListLength(myList len)
message("List length = ${len}")

# Get the n-th element from a list (1-based index)
function(ListGet listVar N outVar)
    set(i 0)
    set(result -1)
    foreach(element IN LISTS ${listVar})
        math(EXPR "i" "${i} + 1")
        if("${i}" EQUAL "${N}")
            set(result "${element}")
            break()
        endif()
    endforeach()
    set("${outVar}" "${result}" PARENT_SCOPE)
endfunction()

set(outputVar 0)
ListGet(myList 3 outputVar)
message("element at position 3 : ${outputVar}")

# Append an element (literal value) to a list variable
function(ListAppend listVar element)
    if("${${listVar}}" STREQUAL "")
        set("${listVar}" "${element}" PARENT_SCOPE)
    else()
        set("${listVar}" "${${listVar}};${element}" PARENT_SCOPE)
    endif()
endfunction()

ListAppend(myList 6)
message("myList after appending 6 : [ ${myList} ]")

# Filter elements from a list matching key
function(ListFilter listVar key outVar)
    set(result "")
    foreach(element IN LISTS ${listVar})
        if("${element}" EQUAL "${key}")
            ListAppend(result "${element}")   # FIX: was passing wrong arg
        endif()
    endforeach()
    set("${outVar}" "${result}" PARENT_SCOPE)
endfunction()

set(filterResult "")
ListFilter(myList 2 filterResult)
message("Filtered List = [ ${filterResult} ]")

# Insert elements into a list at a given 1-based index
function(ListInsert listVar index)
    set(result "")
    set(i 0)
    foreach(element IN LISTS ${listVar})
        math(EXPR i "${i} + 1")
        if(${i} EQUAL ${index})
            foreach(newElem IN LISTS ARGN)
                ListAppend(result "${newElem}")
            endforeach()
        endif()
        ListAppend(result "${element}")
    endforeach()
    set("${listVar}" "${result}" PARENT_SCOPE)
endfunction()

ListInsert(myList 2 42 5 28 17 36)
message("myList = [ ${myList} ]")

# Pop element(s) off the back of the list
function(ListPopBack listVar)
    set(result "")
    set(idx 0)

    if(ARGN)  
        set(oringalLength 0)
        set(numElementsToPop 0)
        set(argnIdx 0)
        ListLength("${listVar}" originalLength)
        ListLength("${ARGN}" numElementsToPop)
        foreach(element IN LISTS ${listVar})
            if(${idx} LESS "${numElements} - ${numElementsToPop}")
                ListAppend(result "${element}")
            else()
                set(varName "")
                ListGet("${ARGN}" ${argnIdx} varName)
                set(${varName} ${element} PARENT_SCOPE)
                math(EXPR argnIdx "${argnIdx} + 1")
            endif()
            math(EXPR idx "${idx} + 1")
        endforeach()
    else()
        set(numElements 0)
        ListLength("${listVar}" numElements)
        math(EXPR threshold "${numElements} - 1")  # FIX: pre-compute, not in if()
        foreach(element IN LISTS ${listVar})
            if(${idx} LESS ${threshold})  # FIX: use pre-computed value
                ListAppend(result "${element}")
            endif()
            math(EXPR idx "${idx} + 1")
        endforeach()
    endif()

    set("${listVar}" "${result}" PARENT_SCOPE)
endfunction()

ListPopBack(myList)
message("myList after popping 1 element = [ ${myList} ]")