name: Windows build
on: [push, pull_request]
jobs:
  build-windows-x86:
    name: 'MSVC ${{ matrix.os }}, ${{ matrix.target }}'
    defaults:
      run:
        shell: bash {0}
    strategy:
      matrix:
        os:
          - 2022
          - 2025
        target:
          - x86
          - x64
    runs-on: windows-${{ matrix.os }}
    steps:
    - name: Setup compiler
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.target }}
    
    - name: Setup Ninja
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install ninja        

    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure
      run:  cmake -B build \
            -DCMAKE_CXX_COMPILER=$CXX \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-std=c++23preview -Wall -Wpedantic"

    - name: Build
      run: cmake --build build
